= C++ example project scanned on SonarQube using Bitbucket Cloud pipelines

:note-caption: :information_source:
NOTE: This simple example ignores https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-7[analysis cache] and https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-8[multithreaded execution] both of which can boost analysis significantly.

To analyze a C, C++ and Objective-C project on Bitbucket pipelines with SonarQube, you need to:

. Enable pipelines in your Bitbucket Cloud repository
. Add a repository variable `SONAR_TOKEN` with a token generated in SonarQube (see https://docs.sonarqube.org/latest/user-guide/user-token/[Generating and Using Tokens])
. Add a repository variable `SONAR_HOST_URL` that points to your SonarQube server (e.g., https://example.com:9000)
. In your `bitbucket-pipelines.yml` file:
.. Download the https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-4[`build wrapper`] and wrap your compilation with it
.. Use `sonarqube-scan` pipe with the build wrapper output directory as an extra argument

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:bitbucket-pipelines.yml[bitbucket-pipelines.yml] to see it in practice.

= Documentation

- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C, C++ and Objective-C plugin and its Build Wrapper]
- https://docs.sonarqube.org/latest/analysis/bitbucket-cloud-integration/[Bitbucket Cloud Integration]
- https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-7[Configuring C, C++ and Objective-C analysis cache]
- https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-8[Configuring multithreaded execution]

= Linux\Autotools

A build of the https://github.com/sonarsource-cfamily-examples/code[code repository] on a Linux platform using GNU Autotools build system.

To build the code run:
----
autoreconf --install
./configure
make clean all
----

= Code Description

An example of a flawed C++ code. The https://github.com/sonarsource-cfamily-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sonarsource-cfamily-examples/code[code repository] is forked into other repositories in https://github.com/sonarsource-cfamily-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sonarsource-cfamily-examples?q=linux[Linux]
* https://github.com/sonarsource-cfamily-examples?q=macos[MacOS]
* https://github.com/sonarsource-cfamily-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sonarsource-cfamily-examples?q=cmake[CMake]
* https://github.com/sonarsource-cfamily-examples?q=autotools[GNU Autotools]
* https://github.com/sonarsource-cfamily-examples?q=xcode[Xcode]
* https://github.com/sonarsource-cfamily-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sonarsource-cfamily-examples?q=azure[Azure DevOps]
* https://github.com/sonarsource-cfamily-examples?q=gh-actions[GitHub Actions]
* https://github.com/sonarsource-cfamily-examples?q=travis[Travis]
* https://github.com/sonarsource-cfamily-examples?q=jenkins[Jenkins]
* https://github.com/sonarsource-cfamily-examples?q=gitlab[GitLab CI]
* https://github.com/sonarsource-cfamily-examples?q=bitbucket[BitBucket Pipelines]

Configured for analysis on:

* https://github.com/sonarsource-cfamily-examples?q=-sq[SonarQube]
* https://github.com/sonarsource-cfamily-examples?q=-sc[SonarCloud]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sonarsource-cfamily-examples[this GitHub organization] and the relations between its different repositories.
